apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-service
  template:
    metadata:
      labels:
        app: service-app
    spec:
      containers:
        - name: springboot
          image: juanantoniorr06/kubernetes:service-app
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-service